name = "TrainingBook"
uuid = "2341ea87-aabe-4153-929b-2a5b9716355c"
authors = ["Jonathan Miller jonathan.miller@fieldofnodes.com"]
version = "1.0.0"

[deps]
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
TrainingContent = "93010b99-796c-4ee1-962b-d06f04731a5c"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
